// Indholdet til projektsiderne. Ret her og kør `node scripts/cases/build.mjs`.
// Rækkefølgen styrer "Forrige / Næste projekt" nederst på siderne.
// Felter med HTML (lede, p) skrives som HTML; resten escapes af build-scriptet.

export const cases = [
	{
		slug: 'trackrs',
		name: 'Trackrs',
		thumb: 'project-thumb-trackrs.png',
		description: 'Trackrs er vores eget system til værktøjsstyring med RFID: egen læser-hardware, alarm når værktøj mangler, og en app til iPhone, Android og web.',
		tagline: 'Værktøjsstyring med RFID, egen læser-hardware og besked, når noget mangler.',
		chips: ['Eget produkt', 'iOS · Android · Web', 'Egen hardware'],
		link: { href: 'https://trackrs.dk', label: 'Besøg trackrs.dk' },
		eyebrow: 'Kort fortalt',
		headline: 'Værktøjet skal være i bilen, når man skal bruge det',
		lede: 'Værktøj forsvinder fra varevogne, containere og lagre, og det opdages først, når nogen står og mangler det. <strong>Trackrs sætter et RFID-tag på værktøjet og en læser i bilen eller containeren.</strong> Så ved systemet hele tiden, hvad der er hvor, og siger til, når noget mangler.',
		facts: [
			['Type', 'Eget SaaS-produkt'],
			['Kunder', 'Håndværks- og byggefirmaer'],
			['Platforme', 'iOS, Android, web, RFID-læser'],
			['Start', '2024'],
		],
		shots: [
			{ src: 'trackrs-dashboard.jpg', kind: 'wide', title: 'Dashboard', caption: 'Værktøj på lokationen, hvad der mangler, og hvordan det bliver brugt.', alt: 'Trackrs-dashboard med værktøjsoversigt og statistik' },
			{ src: 'trackrs-app.jpg', kind: 'phone', title: 'Appen', caption: 'Live-status for en lokation: til stede, mangler, uden tag.', alt: 'Trackrs-appen med værktøj på lageret' },
		],
		featuresTitle: 'Fra tag på værktøjet til alarm på telefonen',
		features: [
			['RFID i realtid', 'Læseren melder løbende, hvilke tags den kan se, og appen viser det live.'],
			['Alarm ved manglende værktøj', 'Lås en lokation, og få besked, når noget forlader den.'],
			['QR og stregkoder', 'Til udstyr, der ikke kan bære et RFID-tag.'],
			['Udlån og erklæringer', 'Hvem har hvad, og hvornår kommer det tilbage.'],
			['Serviceskemaer og eftersyn', 'Eftersyn planlægges og dokumenteres på det enkelte stykke værktøj.'],
			['Labelprint', 'Tags og labels printes direkte fra systemet på en Godex-labelprinter.'],
			['Rapporter', 'Blandt andet til forsikring og aktivitetslog.'],
			['Åbent API', 'REST, webhooks og en MCP-server, så AI-assistenter kan slå værktøj op.'],
		],
		processTitle: 'Bygget hele vejen ned til printpladen',
		pull: 'Trackrs er ikke kun en app. Vi har selv bygget læseren, firmwaren, serveren og appen.',
		steps: [
			['Hardware', 'Egen RFID-læser', 'Et ESP32-S3-board med LTE-M og et UHF-RFID-modul, egen firmware og et kabinet tegnet i CAD.'],
			['Backend', 'Læsninger i realtid', 'Læseren sender over MQTT, læsningerne gemmes som tidsserier, og ændringer skubbes live ud til app og web.'],
			['Produkt', 'Én app til alle skærme', 'Samme Expo-kodebase kører på iPhone, Android og i browseren.'],
			['Integration', 'Åbent for andre systemer', 'REST-API, webhooks og en MCP-server gør Trackrs til noget, andre systemer kan bygge videre på.'],
		],
		stack: [
			['App og web', 'Expo / React Native, TypeScript'],
			['Backend', 'ASP.NET Core, SignalR, MQTT'],
			['Data', 'PostgreSQL, InfluxDB'],
			['Hardware', 'ESP32-S3 LTE-M, UHF RFID, egen firmware'],
			['Betaling', 'Stripe'],
			['Integration', 'REST-API, webhooks, MCP'],
		],
	},
	{
		slug: 'milepro',
		name: 'MilePro',
		thumb: 'project-thumb-milepro.png',
		description: 'MilePro er vores eget system til flådestyring: GPS i firmabilerne, live-kort, automatiske ture og en kørebog, der kan afleveres til SKAT.',
		tagline: 'Flådestyring med GPS, live-kort og en kørebog, der skriver sig selv.',
		chips: ['Eget produkt', 'iOS · Web', 'I drift'],
		link: { href: 'https://milepro.dk', label: 'Besøg milepro.dk' },
		eyebrow: 'Kort fortalt',
		headline: 'Håndværkere skal køre, ikke føre kørebog',
		lede: 'Firmabiler kører hver dag, og nogen skal holde styr på, hvor de er, og hvilke ture der var erhverv. <strong>MilePro sætter en GPS i bilen og klarer resten automatisk</strong>: live-kort over flåden, ture der registreres af sig selv, og en kørebog, der kan afleveres til SKAT.',
		facts: [
			['Type', 'Eget SaaS-produkt'],
			['Kunder', 'Håndværk og servicefirmaer'],
			['Platforme', 'iOS, web, GPS-hardware'],
			['Status', 'I drift'],
		],
		shots: [
			{ src: 'milepro-flaade.jpg', kind: 'framed', title: 'Live-flåde', caption: 'Alle biler på ét kort, søgbart på navn og nummerplade.', alt: 'Live-kort over flåden med alle biler' },
			{ src: 'milepro-historik.jpg', kind: 'framed', title: 'Historik', caption: 'Ture med start, slut, km og tid. PDF og CSV med ét tryk.', alt: 'Turhistorik med adresser, kilometer og tider' },
			{ src: 'milepro-braendstof.jpg', kind: 'framed', title: 'Brændstof', caption: 'Tankninger hentes direkte fra Circle K-kortene.', alt: 'Brændstofoversigt fra Circle K-kort' },
			{ src: 'milepro-leverandorer.jpg', kind: 'framed', title: 'Leverandører', caption: 'Besøg hos grossister registreres automatisk.', alt: 'Leverandøroversigt med grossister' },
		],
		featuresTitle: 'Fra GPS-signal til færdig kørebog',
		features: [
			['Live-kort over flåden', 'Positioner strømmer ind fra trackerne og vises på kortet i realtid.'],
			['Automatiske ture', 'Ture findes ud fra GPS-data, uden at føreren skal trykke på noget.'],
			['Erhverv eller privat', 'Ture klassificeres automatisk, og føreren retter kun det, der er forkert.'],
			['Kørebog til SKAT', 'Månedsrapporter og eksport til PDF og Excel.'],
			['Circle K-integration', 'Brændstofforbruget hentes direkte fra firmaets tankkort.'],
			['Alarmer', 'Besked, når en tracker mister strøm eller bliver taget ud.'],
		],
		processTitle: 'Hardware først, så software',
		pull: 'MilePro taler med fem forskellige GPS-modeller gennem én modtager, vi selv har skrevet.',
		steps: [
			['Hardware', 'Egen GPS-modtager', 'En TCP-server, der forstår protokollerne fra VL110C, VL502, VG502, LL301 og Teltonika FMC003/FMC880.'],
			['Drift', 'Fjernkonfiguration over SMS', 'Trackerne sættes op og genstartes via SIM-kortet, uden at nogen skal ud til bilen.'],
			['Produkt', 'App og web fra samme kodebase', 'Én Expo-app, der kører på iPhone og i browseren.'],
			['Integration', 'Tankkort og partner-API', 'Circle K-data kobles på turene, og partnere kan hente data gennem et åbent API.'],
		],
		stack: [
			['App og web', 'Expo / React Native, TypeScript'],
			['Backend', '.NET 8 API, SignalR'],
			['Data', 'PostgreSQL på Azure'],
			['Hardware', 'Egen TCP-modtager, fem trackermodeller'],
			['Forbindelse', 'IoT-SIM med SMS-konfiguration'],
			['Integration', 'Circle K Fueling API, partner-API'],
		],
	},
	{
		slug: 'mesterplan',
		name: 'Mesterplan',
		thumb: 'project-thumb-mesterplan.png',
		description: 'Mesterplan er vores eget sagsstyringssystem til håndværkere: tilbud, planlægning, timer, e-faktura og AI-tegningsanalyse ét sted.',
		tagline: 'Sagsstyring til håndværkere, fra tilbud til faktura.',
		chips: ['Eget produkt', 'Web · App', 'Beta'],
		link: { href: 'https://mesterplan.dk', label: 'Besøg mesterplan.dk' },
		eyebrow: 'Kort fortalt',
		headline: 'Hele sagen ét sted',
		lede: 'En håndværksmester har ofte tilbud i ét program, timer i et andet og fakturaer i et tredje. <strong>Mesterplan samler sagen</strong>: tilbud, planlægning, timer, materialer og faktura, koblet direkte til regnskabet.',
		facts: [
			['Type', 'Eget SaaS-produkt'],
			['Kunder', 'Håndværks- og byggefirmaer'],
			['Platforme', 'Web og app'],
			['Status', 'Beta med pilotfirmaer'],
		],
		shots: [
			{ src: 'mesterplan-tegningsanalyse.jpg', kind: 'wide', title: 'Tegningsanalyse', caption: 'Upload en tegning og få mængderne, før I byder. Eksemplet er anonymiseret.', alt: 'Mesterplan tegningsanalyse med facadetegning og AI-svar' },
			{ src: 'mesterplan-chat.jpg', kind: 'phone', title: 'Spørg om tegningen', caption: 'Svarene holder sig til tegningen og siger til, når de ikke kan vide det.', alt: 'Chat om en tegning i Mesterplan' },
		],
		featuresTitle: 'Fra første tegning til betalt faktura',
		features: [
			['Tilbud fra prisbibliotek', 'Tilbud bygges af firmaets egne priser og varer.'],
			['Tegningsanalyse med AI', 'Tæller vinduer og døre på PDF-tegninger og viser, hvor sikkert tallet er.'],
			['E-faktura fra grossister', 'Fakturaer kommer ind via NemHandel og matches automatisk til sagen.'],
			['Timer, materialer og kalender', 'Planlægning og registrering fra telefonen, også offline.'],
			['Underentreprenører', 'Inviteres ind på én sag uden at se resten af firmaet.'],
			['Kvalitetssikring', 'Tjeklister og dokumentation på sagen.'],
			['Rapporter', 'En rapportbygger, hvor firmaet selv sætter sine rapporter sammen.'],
			['Regnskab', 'Forbundet med e-conomic og Dinero.'],
		],
		processTitle: 'Bygget sammen med dem, der bruger det',
		pull: 'AI-tallene er vejledende, og det står der. En mester skal kunne stole på et tilbud.',
		steps: [
			['Pilotfirmaer', 'Én ønskeliste ad gangen', 'Pilotfirmaerne sender ønsker og fejl, og vi arbejder dem igennem punkt for punkt.'],
			['Integration', 'Koblet på det, firmaet har', 'e-conomic, Dinero og NemHandel, så fakturaer og bilag ikke skal tastes to gange.'],
			['AI', 'AI, der viser sin usikkerhed', 'Tegningsanalysen giver et tal og en sikkerhed, og mængderne skal efterses, før de går i et tilbud.'],
			['Åbning', 'MCP-server', 'Mesterplan kan bruges direkte fra AI-assistenter.'],
		],
		stack: [
			['Web', 'React 19, Vite, TypeScript'],
			['App', 'Expo / React Native'],
			['Backend', '.NET, Azure Container Apps'],
			['E-faktura', 'NemHandel'],
			['Regnskab', 'e-conomic, Dinero'],
			['AI', 'Tegningsanalyse, MCP-server'],
		],
	},
	{
		slug: 'akkordly',
		name: 'Akkordly',
		thumb: 'project-thumb-akkordly.png',
		description: 'Akkordly er vores eget værktøj til akkordregnskab for stilladsarbejdere, bygget på Stilladspriskuranten.',
		tagline: 'Akkordregnskab for stilladsarbejdere efter Stilladspriskuranten.',
		chips: ['Eget produkt', 'App · Web', 'MVP'],
		link: { href: 'https://app.akkordly.dk', label: 'Åbn Akkordly' },
		eyebrow: 'Kort fortalt',
		headline: 'Akkorden regnet ud ved stilladset',
		lede: 'Stilladsarbejdere arbejder på akkord, og akkorden regnes ud fra en priskurant med tillæg for højde, transport og telt. Det foregår tit på papir og i regneark. <strong>Akkordly regner det ud på telefonen</strong>, mens man står ved stilladset.',
		facts: [
			['Type', 'Eget produkt'],
			['Kunder', 'Stilladsfirmaer og sjak'],
			['Platforme', 'App og web'],
			['Status', 'MVP'],
		],
		shots: [],
		featuresTitle: 'Det, en sjakbajs skal bruge',
		features: [
			['Priskuranten indbygget', 'Stilladspriskuranten 2025 ligger i appen, så man vælger i stedet for at slå op.'],
			['Tillæg', 'Højde, transport og telt regnes med automatisk.'],
			['Akkordregnskab pr. sag', 'Løbende overblik over, hvad sagen er værd.'],
			['QR på stilladsdele', 'Scan og print QR-koder til materiellet.'],
			['Dagsedler', 'Dagens arbejde registreres, mens det er frisk.'],
			['Fordeling i sjakket', 'Overskuddet fordeles mellem sjakkets folk.'],
		],
		processTitle: 'Fra prototype til platform',
		steps: [
			['Prototype', 'Hurtigt ud at prøve', 'Første version blev bygget på Firebase for at komme hurtigt ud til brugerne.'],
			['Platform', 'Flyttet til fælles backend', 'Da idéen holdt, blev Akkordly flyttet over på den samme .NET-platform som vores andre produkter.'],
		],
		stack: [
			['App', 'Expo / React Native'],
			['Web', 'React, TypeScript'],
			['Backend', '.NET'],
		],
	},
	{
		slug: 'leiga',
		name: 'Leiga',
		thumb: 'project-thumb-leiga.png',
		description: 'Leiga er vores eget system til udlejning og service af lifte, hejs og maskiner.',
		tagline: 'Udlejnings- og serviceplatform til lift- og hejsebranchen.',
		chips: ['Eget produkt', 'Web · App', 'Under udvikling'],
		eyebrow: 'Kort fortalt',
		headline: 'Maskinens liv ét sted',
		lede: 'Et udlejningsfirma skal vide, hvor hver maskine står, hvornår den skal til eftersyn, hvilke certifikater der udløber, og hvilken kontrakt den kører på. <strong>Leiga samler det hele på maskinen</strong>, fra lager til udlejning til service.',
		facts: [
			['Type', 'Eget produkt'],
			['Kunder', 'Lift-, hejse- og maskinudlejere'],
			['Platforme', 'Web og app'],
			['Status', 'Under udvikling'],
		],
		shots: [],
		featuresTitle: 'Udlejning og service i samme system',
		features: [
			['Maskinens status', 'Fra lager til udlejet til service, med historik.'],
			['Certifikater', 'Varsel, før et certifikat udløber.'],
			['Kontrakter', 'Leje, lease og serviceaftaler.'],
			['Serviceopgaver', '26 opgavetyper med tjeklister og tidtagning.'],
			['Serviceskabeloner', 'Eftersyn efter interval eller driftstimer.'],
			['Dokumenter til kunden', 'Links, kunden kan åbne uden at logge ind.'],
		],
		stack: [
			['Web', 'React, Vite, TypeScript'],
			['App', 'Expo / React Native'],
			['Backend', '.NET'],
		],
	},
	{
		slug: 'intrahub',
		name: 'IntraHub',
		thumb: 'project-thumb-intrahub.png',
		description: 'IntraHub er vores eget intranet med APV: nyheder, dokumenter, opgaver og arbejdspladsvurdering i én app.',
		tagline: 'Intranet og APV samlet i én app.',
		chips: ['Eget produkt', 'Android · Web', 'I drift'],
		link: { href: 'https://intrahub.dk', label: 'Besøg intrahub.dk' },
		eyebrow: 'Kort fortalt',
		headline: 'APV\'en, hvor medarbejderne allerede er',
		lede: 'Arbejdspladsvurderingen er lovpligtig, men lever ofte i et regneark, som ingen åbner. <strong>IntraHub lægger APV\'en samme sted</strong>, som medarbejderne læser nyheder, finder dokumenter og får opgaver.',
		facts: [
			['Type', 'Eget produkt'],
			['Kunder', 'Danske virksomheder'],
			['Platforme', 'Web og Android'],
			['Status', 'På Google Play siden 2024'],
		],
		shots: [],
		featuresTitle: 'Intranettet og APV\'en i samme app',
		features: [
			['APV', 'Arbejdspladsvurderinger med spørgsmål, som AI hjælper med at formulere.'],
			['Opslag', 'Nyheder og beskeder til hele firmaet.'],
			['Dokumenter', 'Filer og håndbøger ét sted.'],
			['Projekter og opgaver', 'Hvem gør hvad, og hvornår.'],
			['Medarbejdere', 'Oversigt over firmaets folk.'],
			['Forløb', 'Faste forløb, fx ved fratrædelse.'],
		],
		stack: [
			['Web', 'Next.js 15, React 19'],
			['App', 'Expo / React Native'],
			['Backend', 'Firebase, Cloud Functions'],
		],
	},
	{
		slug: 'akui',
		name: 'Akui',
		thumb: 'project-thumb-akui.png',
		description: 'Akui er vores eget værktøj til AI-mødereferater: optag mødet, få en transskription og et referat, og følg op.',
		tagline: 'AI-mødereferater: optag, transskribér, opsummér og følg op.',
		chips: ['Eget produkt', 'iOS · Android · Web', 'Under udvikling'],
		eyebrow: 'Kort fortalt',
		headline: 'Mødet er først nyttigt, når nogen har skrevet det ned',
		lede: 'Efter et møde skal nogen skrive ned, hvad der blev aftalt, og sørge for, at det bliver fulgt op. <strong>Akui optager mødet og laver transskription og referat</strong>, så opfølgningen ikke afhænger af, hvem der tog noter.',
		facts: [
			['Type', 'Eget produkt'],
			['Kunder', 'Virksomheder med mange møder'],
			['Platforme', 'iOS, Android og web'],
			['Status', 'Under udvikling'],
		],
		shots: [],
		featuresTitle: 'Fra optagelse til referat',
		features: [
			['Optagelse i baggrunden', 'Fortsætter på låseskærmen og styres fra Dynamic Island på iPhone og en notifikation på Android.'],
			['Transskription', 'Talen bliver til tekst automatisk.'],
			['Referat', 'Et kort referat med beslutninger og opgaver.'],
			['Eget valg af AI', 'Firmaet vælger selv AI-udbyder og kan bruge sine egne, krypterede nøgler.'],
		],
		processTitle: 'Native, hvor det gælder',
		steps: [
			['App', 'Optagelse, der ikke stopper', 'Egne native moduler i Swift og Kotlin holder optagelsen kørende, når telefonen låses.'],
			['Platform', 'Sammen med de andre produkter', 'Akui er tænkt til at kunne hente data fra vores andre systemer gennem deres MCP-servere.'],
		],
		stack: [
			['App', 'Expo, Swift (ActivityKit), Kotlin'],
			['Web', 'React, Vite'],
			['Backend', '.NET, PostgreSQL'],
			['AI', 'OpenAI-transskription, Anthropic Claude'],
		],
	},
	{
		// Satsregisteret har sin egen, håndskrevne side. Den er med her, så den indgår i "Forrige / Næste".
		slug: 'satser',
		name: 'Satsregisteret',
		external: true,
	},
	{
		slug: 'region-h',
		name: 'Region Hovedstaden',
		thumb: 'project-thumb-region-h.png',
		draft: 'Afventer godkendelse: må Region Hovedstaden og Capgemini nævnes, og er DFPK (patientkald) en del af casen?',
		description: 'Udviklerarbejde for Region Hovedstaden på en intern sundhedsplatform, først som konsulent og siden gennem Rasmussen Solutions.',
		tagline: 'Udvikler i Scrum-teamet bag en af regionens sundhedsplatforme.',
		chips: ['Kundecase', 'Sundhed', 'Web'],
		eyebrow: 'Kundecase · Sundhed',
		headline: 'En plads i teamet, ikke et projekt ved siden af',
		lede: 'SimpleSP er en webplatform i Region Hovedstaden. Den udvikles af et Scrum-team med ni udviklere og en product owner fra regionen. <strong>Vi har været en fast del af teamet</strong>, først fra 2023 til 2025 og igen i 2026.',
		facts: [
			['Kunde', 'Region Hovedstaden'],
			['Rolle', 'Fullstack-udvikler i Scrum-team'],
			['Periode', '2023–2025 og 2026'],
			['Team', '9 udviklere + product owner'],
		],
		shots: [],
		featuresTitle: 'Det, vi byggede',
		features: [
			['Local PRO', 'Upload og import af dokumenter.'],
			['Dashboard', 'Statistik med dynamiske datointervaller.'],
			['Implantater', 'Oprettelse og redigering, inkl. GTIN-numre.'],
			['Smartphrase-notater', 'Genvej til standardtekster i notater.'],
			['Releasekalender (2026)', 'Excel-import, håndtering af dubletter og releases fra Azure DevOps vist direkte i kalenderen.'],
			['Vedligehold', 'Blandt andet opgradering af komponentbiblioteket PrimeReact.'],
		],
		processTitle: 'Sådan arbejdede vi',
		steps: [
			['Team', 'Scrum med regionen', 'Sprints, fælles backlog og en product owner fra regionen.'],
			['Leverance', 'Azure DevOps', 'Kode, review og pipelines i regionens Azure DevOps.'],
		],
		stack: [
			['Frontend', 'React 18, TypeScript, PrimeReact, React Query'],
			['Backend', 'C# / .NET, MariaDB'],
			['Drift', 'Azure DevOps, Azure Pipelines'],
		],
	},
	{
		slug: 'birdie',
		name: 'Birdie',
		thumb: 'project-thumb-birdie.png',
		draft: 'Afventer godkendelse: hvad var aftalen med Birdie og Parhelion, og må Birdies logo bruges?',
		description: 'Rasmussen Solutions hjalp Birdie Scandinavia med at få appen til deres indeklimamåler udgivet i App Store.',
		tagline: 'App til Birdies indeklimamåler, forbundet over Bluetooth.',
		chips: ['Kundecase', 'Forbrugerapp', 'Bluetooth'],
		eyebrow: 'Kundecase · Forbrugerapp',
		headline: 'Over målstregen og ind i App Store',
		lede: 'Birdie laver en lille indeklimamåler til hjemmet. Appen forbinder til måleren over Bluetooth og viser luftkvalitet, fugt, temperatur, skimmelrisiko og pollen. <strong>Appen blev bygget sammen med Parhelion Software, og vores del var sidste stræk</strong>: udgivelse, login og rettelser efter kundens feedback.',
		facts: [
			['Kunde', 'Birdie Scandinavia ApS'],
			['Rolle', 'Udgivelse og færdiggørelse'],
			['Periode', '2025'],
			['Samarbejde', 'Parhelion Software'],
		],
		shots: [],
		featuresTitle: 'Det, vi lavede',
		features: [
			['App Store-udgivelse', 'Appen gjort klar og udgivet i App Store.'],
			['Log ind med Apple', 'Sign in with Apple ved siden af Google og Facebook.'],
			['Rettelser efter feedback', 'Brugerfladen tilpasset efter Birdies egne tilbagemeldinger.'],
			['Overdragelse', 'Koden flyttet til Birdies eget repository.'],
		],
		stack: [
			['App', 'Expo 52, React Native, TypeScript'],
			['Hardware', 'Bluetooth Low Energy'],
			['Login', 'Firebase Auth, Apple, Google, Facebook'],
		],
	},
	{
		slug: 'toogoodtogo',
		name: 'Too Good To Go',
		thumb: 'project-thumb-toogoodtogo.png',
		draft: 'Tekst mangler: hvad lavede vi for Too Good To Go, hvornår, i hvilken rolle, og må logoet bruges?',
		description: 'Kundecase: Too Good To Go.',
		tagline: 'Tekst følger.',
		chips: ['Kundecase'],
		eyebrow: 'Kundecase',
		headline: 'Too Good To Go',
		todo: 'Her skal stå, hvad opgaven var, hvordan samarbejdet var sat op, og hvad vi leverede.',
		facts: [
			['Kunde', 'Too Good To Go'],
			['Rolle', '–'],
			['Periode', '–'],
			['Team', '–'],
		],
		shots: [],
	},
	{
		slug: 'ufst',
		name: 'UFST',
		thumb: 'project-thumb-ufst.png',
		draft: 'Tekst mangler: hvad lavede vi for Udviklings- og Forenklingsstyrelsen, hvornår, i hvilken rolle, og må logoet bruges?',
		description: 'Kundecase: Udviklings- og Forenklingsstyrelsen (UFST).',
		tagline: 'Tekst følger.',
		chips: ['Kundecase', 'Offentlig'],
		eyebrow: 'Kundecase · Offentlig',
		headline: 'Udviklings- og Forenklingsstyrelsen',
		todo: 'Her skal stå, hvad opgaven var, hvordan samarbejdet var sat op, og hvad vi leverede.',
		facts: [
			['Kunde', 'UFST'],
			['Rolle', '–'],
			['Periode', '–'],
			['Team', '–'],
		],
		shots: [],
	},
];
