// Indholdet til projektsiderne. Ret her og kør `node scripts/cases/build.mjs`.
// Rækkefølgen styrer "Forrige / Næste projekt" nederst på siderne.
// Felter med HTML (lede, p) skrives som HTML; resten escapes af build-scriptet.

export const cases = [
	{
		slug: 'trackrs',
		name: 'Trackrs',
		thumb: 'project-thumb-trackrs.png',
		description: 'Trackrs er vores eget system til værktøjsstyring med RFID: egen læser-hardware, alarm når værktøj mangler, og en app til iPhone, Android og web.',
		tagline: 'Værktøjsstyring med RFID, egen læser-hardware og besked, når noget mangler.',
		chips: ['Eget produkt', 'iOS · Android · Web', 'Egen hardware'],
		link: { href: 'https://trackrs.dk', label: 'Besøg trackrs.dk' },
		eyebrow: 'Kort fortalt',
		headline: 'Værktøjet skal være i bilen, når man skal bruge det',
		lede: 'Værktøj forsvinder fra varevogne, containere og lagre, og det opdages først, når nogen står og mangler det. <strong>Trackrs sætter et RFID-tag på værktøjet og en læser i bilen eller containeren.</strong> Så ved systemet hele tiden, hvad der er hvor, og siger til, når noget mangler.',
		facts: [
			['Type', 'Eget SaaS-produkt'],
			['Kunder', 'Håndværks- og byggefirmaer'],
			['Platforme', 'iOS, Android, web, RFID-læser'],
			['Start', '2024'],
		],
		shots: [
			{ src: 'trackrs-dashboard.jpg', kind: 'wide', title: 'Dashboard', caption: 'Værktøj på lokationen, hvad der mangler, og hvordan det bliver brugt.', alt: 'Trackrs-dashboard med værktøjsoversigt og statistik' },
			{ src: 'trackrs-app.jpg', kind: 'phone', title: 'Appen', caption: 'Live-status for en lokation: til stede, mangler, uden tag.', alt: 'Trackrs-appen med værktøj på lageret' },
		],
		featuresTitle: 'Fra tag på værktøjet til alarm på telefonen',
		features: [
			['RFID i realtid', 'Læseren melder løbende, hvilke tags den kan se, og appen viser det live.'],
			['Alarm ved manglende værktøj', 'Lås en lokation, og få besked, når noget forlader den.'],
			['QR og stregkoder', 'Til udstyr, der ikke kan bære et RFID-tag.'],
			['Udlån og erklæringer', 'Hvem har hvad, og hvornår kommer det tilbage.'],
			['Serviceskemaer og eftersyn', 'Eftersyn planlægges og dokumenteres på det enkelte stykke værktøj.'],
			['Labelprint', 'Tags og labels printes direkte fra systemet på en Godex-labelprinter.'],
			['Rapporter', 'Blandt andet til forsikring og aktivitetslog.'],
			['Åbent API', 'REST, webhooks og en MCP-server, så AI-assistenter kan slå værktøj op.'],
		],
		processTitle: 'Bygget hele vejen ned til printpladen',
		pull: 'Trackrs er ikke kun en app. Vi har selv bygget læseren, firmwaren, serveren og appen.',
		steps: [
			['Hardware', 'Egen RFID-læser', 'Et ESP32-S3-board med LTE-M og et UHF-RFID-modul, egen firmware og et kabinet tegnet i CAD.'],
			['Backend', 'Læsninger i realtid', 'Læseren sender over MQTT, læsningerne gemmes som tidsserier, og ændringer skubbes live ud til app og web.'],
			['Produkt', 'Én app til alle skærme', 'Samme Expo-kodebase kører på iPhone, Android og i browseren.'],
			['Integration', 'Åbent for andre systemer', 'REST-API, webhooks og en MCP-server gør Trackrs til noget, andre systemer kan bygge videre på.'],
		],
		stack: [
			['App og web', 'Expo / React Native, TypeScript'],
			['Backend', 'ASP.NET Core, SignalR, MQTT'],
			['Data', 'PostgreSQL, InfluxDB'],
			['Hardware', 'ESP32-S3 LTE-M, UHF RFID, egen firmware'],
			['Betaling', 'Stripe'],
			['Integration', 'REST-API, webhooks, MCP'],
		],
	},
	{
		slug: 'milepro',
		name: 'MilePro',
		thumb: 'project-thumb-milepro.png',
		description: 'MilePro er vores eget system til flådestyring: GPS i firmabilerne, live-kort, automatiske ture og en kørebog, der kan afleveres til SKAT.',
		tagline: 'Flådestyring med GPS, live-kort og en kørebog, der skriver sig selv.',
		chips: ['Eget produkt', 'iOS · Web', 'I drift'],
		link: { href: 'https://milepro.dk', label: 'Besøg milepro.dk' },
		eyebrow: 'Kort fortalt',
		headline: 'Håndværkere skal køre, ikke føre kørebog',
		lede: 'Firmabiler kører hver dag, og nogen skal holde styr på, hvor de er, og hvilke ture der var erhverv. <strong>MilePro sætter en GPS i bilen og klarer resten automatisk</strong>: live-kort over flåden, ture der registreres af sig selv, og en kørebog, der kan afleveres til SKAT.',
		facts: [
			['Type', 'Eget SaaS-produkt'],
			['Kunder', 'Håndværk og servicefirmaer'],
			['Platforme', 'iOS, web, GPS-hardware'],
			['Status', 'I drift'],
		],
		shots: [
			{ src: 'milepro-flaade.jpg', kind: 'framed', title: 'Live-flåde', caption: 'Alle biler på ét kort, søgbart på navn og nummerplade.', alt: 'Live-kort over flåden med alle biler' },
			{ src: 'milepro-historik.jpg', kind: 'framed', title: 'Historik', caption: 'Ture med start, slut, km og tid. PDF og CSV med ét tryk.', alt: 'Turhistorik med adresser, kilometer og tider' },
			{ src: 'milepro-braendstof.jpg', kind: 'framed', title: 'Brændstof', caption: 'Tankninger hentes direkte fra Circle K-kortene.', alt: 'Brændstofoversigt fra Circle K-kort' },
			{ src: 'milepro-leverandorer.jpg', kind: 'framed', title: 'Leverandører', caption: 'Besøg hos grossister registreres automatisk.', alt: 'Leverandøroversigt med grossister' },
		],
		featuresTitle: 'Fra GPS-signal til færdig kørebog',
		features: [
			['Live-kort over flåden', 'Positioner strømmer ind fra trackerne og vises på kortet i realtid.'],
			['Automatiske ture', 'Ture findes ud fra GPS-data, uden at føreren skal trykke på noget.'],
			['Erhverv eller privat', 'Ture klassificeres automatisk, og føreren retter kun det, der er forkert.'],
			['Kørebog til SKAT', 'Månedsrapporter og eksport til PDF og Excel.'],
			['Circle K-integration', 'Brændstofforbruget hentes direkte fra firmaets tankkort.'],
			['Alarmer', 'Besked, når en tracker mister strøm eller bliver taget ud.'],
		],
		processTitle: 'Hardware først, så software',
		pull: 'MilePro taler med fem forskellige GPS-modeller gennem én modtager, vi selv har skrevet.',
		steps: [
			['Hardware', 'Egen GPS-modtager', 'En TCP-server, der forstår protokollerne fra VL110C, VL502, VG502, LL301 og Teltonika FMC003/FMC880.'],
			['Drift', 'Fjernkonfiguration over SMS', 'Trackerne sættes op og genstartes via SIM-kortet, uden at nogen skal ud til bilen.'],
			['Produkt', 'App og web fra samme kodebase', 'Én Expo-app, der kører på iPhone og i browseren.'],
			['Integration', 'Tankkort og partner-API', 'Circle K-data kobles på turene, og partnere kan hente data gennem et åbent API.'],
		],
		stack: [
			['App og web', 'Expo / React Native, TypeScript'],
			['Backend', '.NET 8 API, SignalR'],
			['Data', 'PostgreSQL på Azure'],
			['Hardware', 'Egen TCP-modtager, fem trackermodeller'],
			['Forbindelse', 'IoT-SIM med SMS-konfiguration'],
			['Integration', 'Circle K Fueling API, partner-API'],
		],
	},
	{
		slug: 'mesterplan',
		name: 'Mesterplan',
		thumb: 'project-thumb-mesterplan.png',
		description: 'Mesterplan er vores eget sagsstyringssystem til håndværkere: tilbud, sager og delprojekter, planlægning, fakturering efter stade, e-faktura via NemHandel, prisfiler fra grossisten, e-conomic og Danløn.',
		tagline: 'Sagsstyring til håndværkere, fra tilbud til faktura.',
		chips: ['Eget produkt', 'Web · App', 'Beta'],
		link: { href: 'https://mesterplan.dk', label: 'Besøg mesterplan.dk' },
		eyebrow: 'Kort fortalt',
		headline: 'Hele sagen ét sted',
		lede: 'En håndværksmester har ofte tilbud i ét program, timer i et andet, fakturaer fra grossisten i en mailboks og regnskabet hos bogholderen. <strong>Mesterplan samler sagen</strong>: tilbud, planlægning, timer, materialer og faktura, koblet direkte til grossisten, regnskabet og lønnen.',
		facts: [
			['Type', 'Eget SaaS-produkt'],
			['Kunder', 'Håndværks- og byggefirmaer'],
			['Platforme', 'Web og app'],
			['Status', 'Beta med pilotfirmaer'],
		],
		shots: [
			{ src: 'mesterplan-planlaegning.jpg', kind: 'wide', title: 'Planlægning', caption: 'Hvem er hvor, hvornår. Gantt, dag, uge og måned, med teams og fravær. Demo-data.', alt: 'Mesterplan planlægning med medarbejdere fordelt på teams' },
		],
		chapters: [
			{
				eyebrow: 'Sagsstyring',
				status: ['live', 'I drift'],
				title: 'Fra tilbud til sag til faktura',
				body: [
					'Alt i Mesterplan hænger på sagen. Et tilbud får sit eget fortløbende nummer, og når kunden siger ja, bliver det til en sag med ét klik. Kalkulationen følger med, så budgettet på sagen er det, der blev lovet i tilbuddet.',
					'Store opgaver kan deles op i delprojekter. Hvert delprojekt får sit eget nummer under hovedsagen, fx 1001-1 og 1001-2, med eget budget, egne timer og egne materialer.',
				],
				points: [
					'<b>Tilbud</b> fra firmaets eget prisbibliotek, sendt som PDF, hvor firmaet selv vælger, hvilke afsnit kunden ser.',
					'<b>Timer og materialer</b> registreres på sagen fra telefonen, også uden dækning. Appen gemmer og sender, når forbindelsen er tilbage.',
					'<b>Planlægning</b> af folk og opgaver i Gantt, dag, uge og måned, med teams, fravær og ferie.',
					'<b>Aftalesedler, budget og rapporter</b>, så mesteren kan se, om sagen tjener penge, mens den kører.',
				],
			},
			{
				eyebrow: 'Fakturering',
				status: ['live', 'I drift'],
				title: 'Faktura efter stade',
				body: [
					'De fleste håndværkssager faktureres i rater. Mesterplan lader mesteren fakturere efter stade på hver linje i tilbudslisten, i kroner eller procent, både på hovedsagen og på delprojekterne.',
					'Bagefter viser sagen, hvor meget der er faktureret, og hvad der mangler, fordelt på hovedsag og delprojekter.',
				],
				shots: [
					{ src: 'mesterplan-stade.jpg', kind: 'panel', title: 'Opret faktura', caption: 'Stade pr. position, i kr. eller %. Demo-data.', alt: 'Fakturering efter stade med hovedsag og delprojekter' },
					{ src: 'mesterplan-fordeling.jpg', kind: 'wide', title: 'Fordeling pr. sag', caption: 'Kontraktsum, faktureret og rest for hovedsag og delprojekter. Demo-data.', alt: 'Tabel over fakturering fordelt på delprojekter' },
				],
			},
			{
				eyebrow: 'AI-tegningsanalyse',
				status: ['live', 'I drift'],
				title: 'Mængderne ud af tegningen, før I byder',
				body: [
					'Mesteren uploader en PDF-tegning og får et mængdeudtag: vinduer, døre, formsten, fuger og arealer. Hvert tal har en sikkerhed, og usikre tal er markeret, så man ved, hvad der skal tjekkes, før det går i et tilbud.',
					'Man kan også stille spørgsmål til tegningen. Svarene holder sig til det, der står på tegningen, og siger til, når de ikke kan vide det.',
				],
				shots: [
					{ src: 'mesterplan-tegningsanalyse.jpg', kind: 'wide', title: 'Tegningsanalyse', caption: 'Upload en tegning og få mængderne, før I byder. Eksemplet er anonymiseret.', alt: 'Mesterplan tegningsanalyse med facadetegning og AI-svar' },
					{ src: 'mesterplan-maengdeudtag.jpg', kind: 'wide', title: 'Mængdeudtag', caption: 'Hver post med antal, enhed og sikkerhed. Eksemplet er anonymiseret.', alt: 'Mængdeudtag fra en facadetegning med usikkerhed pr. post' },
					{ src: 'mesterplan-chat.jpg', kind: 'phone', title: 'Spørg om tegningen', caption: 'Svar, der holder sig til tegningen.', alt: 'Chat om en tegning i Mesterplan' },
				],
			},
			{
				eyebrow: 'E-faktura via NemHandel',
				status: ['rollout', 'Rulles ud'],
				title: 'Grossistens faktura finder selv sagen',
				body: [
					'Grossisterne sender deres fakturaer som e-faktura over NemHandel. Mesterplan tager imod dem og læser sagsnummeret i fakturaens reference. Passer det til en sag, bliver fakturalinjerne automatisk til materialer på sagen. Passer det ikke, lander fakturaen i en indbakke, hvor den kan lægges på den rigtige sag med et par klik.',
					'Modtagelsen kører i dag på vores egen virksomhed og rulles nu ud til kunderne.',
				],
			},
			{
				eyebrow: 'Prisfiler fra grossisten',
				status: ['live', 'I drift'],
				title: 'Bygmas prisbog direkte ind i prisbiblioteket',
				body: [
					'Et tilbud er kun så godt som priserne bag det. Mesterplan kan indlæse Bygmas prisbog, hele kataloget med brutto- og nettopriser og EAN-numre. Vi har testet det på en rigtig prisfil med over 13.000 varer.',
					'En ny prisfil erstatter den gamle i én omgang, og varerne sorteres automatisk i firmaets varegrupper efter ByggeBasens inddeling. Ved siden af har firmaet sit eget prisbibliotek til egne ydelser og kalkulationer. Flere grossister er på vej.',
				],
			},
			{
				eyebrow: 'Regnskab',
				status: ['live', 'I drift'],
				title: 'e-conomic, uden at taste to gange',
				body: [
					'Mesterplan er koblet til e-conomic. Kunder og produkter synkroniseres, fakturaer oprettes og bogføres i e-conomic, og betalinger registreres, så sagen ved, hvad der er betalt.',
					'Opsætningen henter kladder, konti og produkter direkte fra e-conomic-aftalen, og hver bilagskategori, fx materialer, værktøj og underentreprenører, får sin egen konto. Dinero kan også forbindes.',
				],
				shots: [
					{ src: 'mesterplan-economic.jpg', kind: 'wide', title: 'e-conomic-opsætning', caption: 'Kladder, konti og produkter hentes fra e-conomic. Kontomapping pr. bilagskategori.', alt: 'Indstillinger for e-conomic-bogføring i Mesterplan' },
				],
			},
			{
				eyebrow: 'Løn',
				status: ['rollout', 'Rulles ud'],
				title: 'Timerne videre til Danløn',
				body: [
					'Timerne er allerede registreret på sagerne, så de skal ikke tastes igen til lønnen. Mesterplan sender dem til Danløn som lønarter, med medarbejdere og lønkoder koblet sammen én gang for alle.',
					'Danløn-integrationen er bygget og sættes nu i drift hos de første kunder. Zenegy, DataLøn og EG Lønservice er på vej.',
				],
			},
			{
				eyebrow: 'Kvalitet og samarbejde',
				status: ['live', 'I drift'],
				title: 'KS, KLS og underentreprenører',
				body: [
					'Kvalitetssikringen ligger på sagen: tjeklister, afvigelser, udstyr og medarbejdernes kompetencer, med skabeloner til KLS.',
					'Underentreprenører kan inviteres ind på én sag uden at se resten af firmaet, og mangler kan sendes ud via et link, der kan åbnes uden login.',
				],
			},
			{
				eyebrow: 'Åben platform',
				status: ['live', 'I drift'],
				title: 'Mesterplan i AI-assistenten',
				body: [
					'Mesterplan har sin egen MCP-server. Det betyder, at en AI-assistent som Claude kan slå sager op, finde kunder og oprette projekter i Mesterplan på brugerens vegne, med de samme rettigheder som brugeren selv.',
					'En kobling til vores værktøjssystem Trackrs er bygget og på vej, så værktøj og omkostninger fra Trackrs kan lande på den rigtige sag.',
				],
			},
		],
		processTitle: 'Bygget sammen med dem, der bruger det',
		pull: 'AI-tallene er vejledende, og det står der. En mester skal kunne stole på et tilbud.',
		steps: [
			['Pilotfirmaer', 'Én ønskeliste ad gangen', 'Pilotfirmaerne sender ønsker og fejl, og vi arbejder dem igennem punkt for punkt.'],
			['Integration', 'Koblet på det, firmaet har', 'Grossist, regnskab og løn, så fakturaer, bilag og timer ikke skal tastes to gange.'],
			['AI', 'AI, der viser sin usikkerhed', 'Tegningsanalysen giver et tal og en sikkerhed, og mængderne skal efterses, før de går i et tilbud.'],
			['Drift', 'Små, sikre skridt', 'Nye funktioner går i drift bag et flag og tændes for én kunde ad gangen.'],
		],
		stack: [
			['Web', 'React 19, Vite, TypeScript'],
			['App', 'Expo / React Native, offline-kø'],
			['Backend', '.NET, Azure Container Apps'],
			['E-faktura', 'NemHandel via Sproom'],
			['Regnskab og løn', 'e-conomic, Dinero, Danløn'],
			['Priser', 'Bygma prisbog (CSV), ByggeBasen-varegrupper'],
			['AI', 'Tegningsanalyse, MCP-server'],
		],
	},
	{
		slug: 'akkordly',
		name: 'Akkordly',
		thumb: 'project-thumb-akkordly.png',
		description: 'Akkordly er vores eget værktøj til akkordregnskab for stilladsarbejdere, bygget på Stilladspriskuranten.',
		tagline: 'Akkordregnskab for stilladsarbejdere efter Stilladspriskuranten.',
		chips: ['Eget produkt', 'App · Web', 'MVP'],
		link: { href: 'https://app.akkordly.dk', label: 'Åbn Akkordly' },
		eyebrow: 'Kort fortalt',
		headline: 'Akkorden regnet ud ved stilladset',
		lede: 'Stilladsarbejdere arbejder på akkord, og akkorden regnes ud fra en priskurant med tillæg for højde, transport og telt. Det foregår tit på papir og i regneark. <strong>Akkordly regner det ud på telefonen</strong>, mens man står ved stilladset.',
		facts: [
			['Type', 'Eget produkt'],
			['Kunder', 'Stilladsfirmaer og sjak'],
			['Platforme', 'App og web'],
			['Status', 'MVP'],
		],
		shots: [],
		featuresTitle: 'Det, en sjakbajs skal bruge',
		features: [
			['Priskuranten indbygget', 'Stilladspriskuranten 2025 ligger i appen, så man vælger i stedet for at slå op.'],
			['Tillæg', 'Højde, transport og telt regnes med automatisk.'],
			['Akkordregnskab pr. sag', 'Løbende overblik over, hvad sagen er værd.'],
			['QR på stilladsdele', 'Scan og print QR-koder til materiellet.'],
			['Dagsedler', 'Dagens arbejde registreres, mens det er frisk.'],
			['Fordeling i sjakket', 'Overskuddet fordeles mellem sjakkets folk.'],
		],
		processTitle: 'Fra prototype til platform',
		steps: [
			['Prototype', 'Hurtigt ud at prøve', 'Første version blev bygget på Firebase for at komme hurtigt ud til brugerne.'],
			['Platform', 'Flyttet til fælles backend', 'Da idéen holdt, blev Akkordly flyttet over på den samme .NET-platform som vores andre produkter.'],
		],
		stack: [
			['App', 'Expo / React Native'],
			['Web', 'React, TypeScript'],
			['Backend', '.NET'],
		],
	},
	{
		slug: 'leiga',
		name: 'Leiga',
		thumb: 'project-thumb-leiga.png',
		description: 'Leiga er vores eget system til udlejning og service af lifte, hejs og maskiner.',
		tagline: 'Udlejnings- og serviceplatform til lift- og hejsebranchen.',
		chips: ['Eget produkt', 'Web · App', 'Under udvikling'],
		eyebrow: 'Kort fortalt',
		headline: 'Maskinens liv ét sted',
		lede: 'Et udlejningsfirma skal vide, hvor hver maskine står, hvornår den skal til eftersyn, hvilke certifikater der udløber, og hvilken kontrakt den kører på. <strong>Leiga samler det hele på maskinen</strong>, fra lager til udlejning til service.',
		facts: [
			['Type', 'Eget produkt'],
			['Kunder', 'Lift-, hejse- og maskinudlejere'],
			['Platforme', 'Web og app'],
			['Status', 'Under udvikling'],
		],
		shots: [],
		featuresTitle: 'Udlejning og service i samme system',
		features: [
			['Maskinens status', 'Fra lager til udlejet til service, med historik.'],
			['Certifikater', 'Varsel, før et certifikat udløber.'],
			['Kontrakter', 'Leje, lease og serviceaftaler.'],
			['Serviceopgaver', '26 opgavetyper med tjeklister og tidtagning.'],
			['Serviceskabeloner', 'Eftersyn efter interval eller driftstimer.'],
			['Dokumenter til kunden', 'Links, kunden kan åbne uden at logge ind.'],
		],
		stack: [
			['Web', 'React, Vite, TypeScript'],
			['App', 'Expo / React Native'],
			['Backend', '.NET'],
		],
	},
	{
		slug: 'intrahub',
		name: 'IntraHub',
		thumb: 'project-thumb-intrahub.png',
		description: 'IntraHub er vores eget system til digital APV og intranet: arbejdspladsvurderinger, handlingsplaner, opslag, dokumenter og forløb i én app til iPhone, Android og web.',
		tagline: 'Digital APV og intranet, med medarbejderne på telefonen.',
		chips: ['Eget produkt', 'iOS · Android · Web', 'I drift'],
		link: { href: 'https://intrahub.dk', label: 'Besøg intrahub.dk' },
		eyebrow: 'Kort fortalt',
		headline: 'APV\'en, hvor medarbejderne allerede er',
		lede: 'Arbejdspladsvurderingen er lovpligtig, men lever ofte på papir eller i et regneark, som ingen åbner. <strong>IntraHub gør APV\'en til noget, medarbejderne svarer på fra telefonen</strong>, og svarene bliver til handlingsplaner med en ansvarlig og en frist. Opslag, aktiviteter og dokumenter ligger samme sted, så der er en grund til at åbne appen.',
		facts: [
			['Type', 'Eget produkt'],
			['Kunder', 'Bygge- og håndværksfirmaer'],
			['Platforme', 'iOS, Android og web'],
			['Status', 'I App Store og Google Play'],
		],
		shots: [
			{ src: 'intrahub-hjem.jpg', kind: 'framed', title: 'Forsiden', caption: 'Mine APV\'er, handlinger og det seneste fra firmaet. Demo-data.', alt: 'IntraHub-appens forside med APV\'er og seneste aktivitet' },
			{ src: 'intrahub-apv-svar.jpg', kind: 'framed', title: 'Medarbejderen svarer', caption: 'Ja/nej og skala på telefonen, spørgsmål for spørgsmål. Demo-data.', alt: 'Medarbejder besvarer en projekt-APV i IntraHub-appen' },
			{ src: 'intrahub-apv-ai.jpg', kind: 'framed', title: 'Generer med AI', caption: 'Spørgsmål i seks kategorier, med ekstra kontekst om projektet.', alt: 'Projekt-APV med knappen Generer med AI' },
			{ src: 'intrahub-menu.jpg', kind: 'framed', title: 'Menuen', caption: 'Handlinger, opgaver, dokumenter og skift mellem virksomheder. Demo-data.', alt: 'IntraHub-appens menu med profil og virksomhed' },
		],
		chapters: [
			{
				eyebrow: 'APV',
				status: ['live', 'I drift'],
				title: 'Fra spørgeskema til handlingsplan',
				body: [
					'IntraHub har to slags APV: én for medarbejderen og én for det enkelte projekt. Spørgsmålene er delt i de seks kategorier fra arbejdsmiljøarbejdet: fysiske, kemiske, biologiske, ergonomiske og psykiske forhold og øvrige risici. Hvert spørgsmål besvares med ja/nej eller på en skala fra 1 til 5.',
					'For hvert spørgsmål bestemmer virksomheden, hvilket svar der er et problem. Så bliver svaret automatisk til en handling med en ansvarlig og en frist, og den ansvarlige kan følge den under Mine handlinger.',
				],
				points: [
					'<b>Påmindelser</b> til medarbejdere, der mangler at svare, og til ansvarlige, hvis frist nærmer sig.',
					'<b>Faste cyklusser</b>, så APV\'en bliver gentaget uden at nogen skal huske det.',
				],
			},
			{
				eyebrow: 'AI',
				status: ['rollout', 'Ny'],
				title: 'Spørgsmålene skrevet til jeres arbejde',
				body: [
					'Det sværeste ved en APV er at stille de rigtige spørgsmål. IntraHub kan skrive dem med AI: ud fra virksomhedens profil og, hvis man vil, projektbeskrivelsen som Word-dokument, foreslår den spørgsmål i hver af de seks kategorier. Til byggeprojekter tager den udgangspunkt i Bygge- og anlægsbekendtgørelsen og PSS.',
					'Forslagene tjekkes, før de vises, og virksomheden retter dem til, inden APV\'en sendes ud. Virksomheden bruger sin egen AI-nøgle, som gemmes krypteret.',
				],
			},
			{
				eyebrow: 'Intranet',
				status: ['live', 'I drift'],
				title: 'Det, medarbejderne åbner appen for',
				body: [
					'En APV-app, man kun åbner én gang om året, bliver glemt. Derfor ligger resten af firmaets hverdag samme sted.',
				],
				points: [
					'<b>Opslag</b> med nyheder og beskeder til hele firmaet.',
					'<b>Aktiviteter</b> med tilmelding og påmindelse før fristen.',
					'<b>Projekter</b> med billeder og status.',
					'<b>Dokumenter</b>, der kan sendes til medarbejderne med kvittering eller underskrift.',
					'<b>Medarbejdere</b> med invitationer, ledere og profilbilleder.',
				],
			},
			{
				eyebrow: 'Forløb',
				status: ['live', 'I drift'],
				title: 'Faste opgaver, der kører af sig selv',
				body: [
					'Nogle ting skal gøres på samme måde hver gang, fx når en medarbejder siger op. Et forløb i IntraHub starter, når noget bliver oprettet, skifter status, på et fast tidspunkt eller med et klik, og fordeler opgaverne til en rolle, til medarbejderens leder eller til den, der startede det.',
					'Der følger færdige danske skabeloner med til fratrædelse og opsigelse.',
				],
			},
			{
				eyebrow: 'Sikkerhed',
				status: ['live', 'I drift'],
				title: 'Hver virksomheds data for sig',
				body: [
					'Administratorer arbejder på web, medarbejderne i appen, og en bruger kan være med i flere virksomheder og skifte mellem dem. Data er adskilt pr. virksomhed direkte i databasens regler, og adskillelsen er dækket af næsten 200 automatiske tjek.',
				],
			},
		],
		processTitle: 'Fra intranet til APV-platform',
		steps: [
			['Start', 'Et intranet', 'IntraHub begyndte som et intranet til virksomheder, netværk og foreninger.'],
			['Fokus', 'APV\'en i centrum', 'I dag er APV\'en omdrejningspunktet, og både spørgsmål og skabeloner er rettet mod bygge- og håndværksfirmaer.'],
			['Opdeling', 'Web til kontoret, app til pladsen', 'Administratorer bygger APV\'er og forløb på web. Medarbejderne svarer og følger op i appen.'],
			['Sikkerhed', 'Adskillelse testet', 'Reglerne for, hvem der må se hvad, blev gennemgået og dækket af automatiske tjek.'],
		],
		stack: [
			['Web', 'Next.js 15, React 19, Netlify'],
			['App', 'Expo / React Native'],
			['Backend', 'Firebase: Firestore, Cloud Functions, Storage'],
			['AI', 'Anthropic Claude, virksomhedens egen krypterede nøgle'],
			['Notifikationer', 'Push og planlagte påmindelser'],
		],
	},
	{
		slug: 'akui',
		name: 'Akui',
		thumb: 'project-thumb-akui.png',
		description: 'Akui er vores eget værktøj til AI-mødereferater: optag mødet, få en transskription og et referat, og følg op.',
		tagline: 'AI-mødereferater: optag, transskribér, opsummér og følg op.',
		chips: ['Eget produkt', 'iOS · Android · Web', 'Under udvikling'],
		eyebrow: 'Kort fortalt',
		headline: 'Mødet er først nyttigt, når nogen har skrevet det ned',
		lede: 'Efter et møde skal nogen skrive ned, hvad der blev aftalt, og sørge for, at det bliver fulgt op. <strong>Akui optager mødet og laver transskription og referat</strong>, så opfølgningen ikke afhænger af, hvem der tog noter.',
		facts: [
			['Type', 'Eget produkt'],
			['Kunder', 'Virksomheder med mange møder'],
			['Platforme', 'iOS, Android og web'],
			['Status', 'Under udvikling'],
		],
		shots: [],
		featuresTitle: 'Fra optagelse til referat',
		features: [
			['Optagelse i baggrunden', 'Fortsætter på låseskærmen og styres fra Dynamic Island på iPhone og en notifikation på Android.'],
			['Transskription', 'Talen bliver til tekst automatisk.'],
			['Referat', 'Et kort referat med beslutninger og opgaver.'],
			['Eget valg af AI', 'Firmaet vælger selv AI-udbyder og kan bruge sine egne, krypterede nøgler.'],
		],
		processTitle: 'Native, hvor det gælder',
		steps: [
			['App', 'Optagelse, der ikke stopper', 'Egne native moduler i Swift og Kotlin holder optagelsen kørende, når telefonen låses.'],
			['Platform', 'Sammen med de andre produkter', 'Akui er tænkt til at kunne hente data fra vores andre systemer gennem deres MCP-servere.'],
		],
		stack: [
			['App', 'Expo, Swift (ActivityKit), Kotlin'],
			['Web', 'React, Vite'],
			['Backend', '.NET, PostgreSQL'],
			['AI', 'OpenAI-transskription, Anthropic Claude'],
		],
	},
	{
		// Satsregisteret har sin egen, håndskrevne side. Den er med her, så den indgår i "Forrige / Næste".
		slug: 'satser',
		name: 'Satsregisteret',
		external: true,
	},
	{
		slug: 'region-h',
		name: 'Region Hovedstaden',
		thumb: 'project-thumb-region-h.png',
		draft: 'Afventer godkendelse: må Region Hovedstaden og Capgemini nævnes, og er DFPK (patientkald) en del af casen?',
		description: 'Udviklerarbejde for Region Hovedstaden på en intern sundhedsplatform, først som konsulent og siden gennem Rasmussen Solutions.',
		tagline: 'Udvikler i Scrum-teamet bag en af regionens sundhedsplatforme.',
		chips: ['Kundecase', 'Sundhed', 'Web'],
		eyebrow: 'Kundecase · Sundhed',
		headline: 'En plads i teamet, ikke et projekt ved siden af',
		lede: 'SimpleSP er en webplatform i Region Hovedstaden. Den udvikles af et Scrum-team med ni udviklere og en product owner fra regionen. <strong>Vi har været en fast del af teamet</strong>, først fra 2023 til 2025 og igen i 2026.',
		facts: [
			['Kunde', 'Region Hovedstaden'],
			['Rolle', 'Fullstack-udvikler i Scrum-team'],
			['Periode', '2023–2025 og 2026'],
			['Team', '9 udviklere + product owner'],
		],
		shots: [],
		featuresTitle: 'Det, vi byggede',
		features: [
			['Local PRO', 'Upload og import af dokumenter.'],
			['Dashboard', 'Statistik med dynamiske datointervaller.'],
			['Implantater', 'Oprettelse og redigering, inkl. GTIN-numre.'],
			['Smartphrase-notater', 'Genvej til standardtekster i notater.'],
			['Releasekalender (2026)', 'Excel-import, håndtering af dubletter og releases fra Azure DevOps vist direkte i kalenderen.'],
			['Vedligehold', 'Blandt andet opgradering af komponentbiblioteket PrimeReact.'],
		],
		processTitle: 'Sådan arbejdede vi',
		steps: [
			['Team', 'Scrum med regionen', 'Sprints, fælles backlog og en product owner fra regionen.'],
			['Leverance', 'Azure DevOps', 'Kode, review og pipelines i regionens Azure DevOps.'],
		],
		stack: [
			['Frontend', 'React 18, TypeScript, PrimeReact, React Query'],
			['Backend', 'C# / .NET, MariaDB'],
			['Drift', 'Azure DevOps, Azure Pipelines'],
		],
	},
	{
		slug: 'birdie',
		name: 'Birdie',
		thumb: 'project-thumb-birdie.png',
		draft: 'Afventer godkendelse: hvad var aftalen med Birdie og Parhelion, og må Birdies logo bruges?',
		description: 'Rasmussen Solutions hjalp Birdie Scandinavia med at få appen til deres indeklimamåler udgivet i App Store.',
		tagline: 'App til Birdies indeklimamåler, forbundet over Bluetooth.',
		chips: ['Kundecase', 'Forbrugerapp', 'Bluetooth'],
		eyebrow: 'Kundecase · Forbrugerapp',
		headline: 'Over målstregen og ind i App Store',
		lede: 'Birdie laver en lille indeklimamåler til hjemmet. Appen forbinder til måleren over Bluetooth og viser luftkvalitet, fugt, temperatur, skimmelrisiko og pollen. <strong>Appen blev bygget sammen med Parhelion Software, og vores del var sidste stræk</strong>: udgivelse, login og rettelser efter kundens feedback.',
		facts: [
			['Kunde', 'Birdie Scandinavia ApS'],
			['Rolle', 'Udgivelse og færdiggørelse'],
			['Periode', '2025'],
			['Samarbejde', 'Parhelion Software'],
		],
		shots: [],
		featuresTitle: 'Det, vi lavede',
		features: [
			['App Store-udgivelse', 'Appen gjort klar og udgivet i App Store.'],
			['Log ind med Apple', 'Sign in with Apple ved siden af Google og Facebook.'],
			['Rettelser efter feedback', 'Brugerfladen tilpasset efter Birdies egne tilbagemeldinger.'],
			['Overdragelse', 'Koden flyttet til Birdies eget repository.'],
		],
		stack: [
			['App', 'Expo 52, React Native, TypeScript'],
			['Hardware', 'Bluetooth Low Energy'],
			['Login', 'Firebase Auth, Apple, Google, Facebook'],
		],
	},
	{
		slug: 'toogoodtogo',
		name: 'Too Good To Go',
		thumb: 'project-thumb-toogoodtogo.png',
		draft: 'Tekst mangler: hvad lavede vi for Too Good To Go, hvornår, i hvilken rolle, og må logoet bruges?',
		description: 'Kundecase: Too Good To Go.',
		tagline: 'Tekst følger.',
		chips: ['Kundecase'],
		eyebrow: 'Kundecase',
		headline: 'Too Good To Go',
		todo: 'Her skal stå, hvad opgaven var, hvordan samarbejdet var sat op, og hvad vi leverede.',
		facts: [
			['Kunde', 'Too Good To Go'],
			['Rolle', '–'],
			['Periode', '–'],
			['Team', '–'],
		],
		shots: [],
	},
	{
		slug: 'ufst',
		name: 'UFST',
		thumb: 'project-thumb-ufst.png',
		draft: 'Tekst mangler: hvad lavede vi for Udviklings- og Forenklingsstyrelsen, hvornår, i hvilken rolle, og må logoet bruges?',
		description: 'Kundecase: Udviklings- og Forenklingsstyrelsen (UFST).',
		tagline: 'Tekst følger.',
		chips: ['Kundecase', 'Offentlig'],
		eyebrow: 'Kundecase · Offentlig',
		headline: 'Udviklings- og Forenklingsstyrelsen',
		todo: 'Her skal stå, hvad opgaven var, hvordan samarbejdet var sat op, og hvad vi leverede.',
		facts: [
			['Kunde', 'UFST'],
			['Rolle', '–'],
			['Periode', '–'],
			['Team', '–'],
		],
		shots: [],
	},
];
